name: build

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    env:
      NAME: yuki
      GO111MODULE: on
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            GOOS: linux 
            GOARCH: amd64

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Golang module cache
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    # TODO: before_script?

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Test
      run: ci/script.sh
    
    - name: Build
      run: ci/build.sh
    
    # TODO: deploy & notification?
